// <auto-generated />
namespace SomeProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SubCountClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SubCountClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201901091626297_SubCountClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
